import React,{useState} from 'react'
import type { NextPage } from 'next'
import jwt from 'jsonwebtoken'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [username, setUsername] = useState<string>('')
  const [password, setPassword] = useState<string>('')
  const [message, setMessage] = useState<string>('you are not logged in')
  const [secret, setSecret] = useState<string>('')
  
  const submitForm = async()=>{
    const res = await fetch('api/login',{
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({username, password})
    }).then((t)=>t.json())
    const token = res.token
    
    if(token){
     
      const json = jwt.decode(token) as {[key: string]: string}
      
      setMessage(`Welcome ${json.username} and you are ${json.admin ? 'an admin!': 'not an admin'}`)

      const res = await fetch('api/secret',{
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({token})
      }).then((t)=>t.json())
      
      if(res.secretAdminCode){
        setSecret(res.secretAdminCode)
      }else{
        setSecret('Nothing avilable')
      }

    }else{
      setMessage('Something went wrong')
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>{message}</h1>
          <h1>Secret: {secret} </h1>
          <form method="POST" action="/api/login">
            <input type="text" name="username" value={username} onChange={(e)=>setUsername(e.target.value)} />
            <br/>
            <input type="password" name="password" value={password} onChange={(e)=>setPassword(e.target.value)} />
            <br/>
            <input type="button" value="Login" onClick={submitForm} />
            <br/>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <div>JWT with Nextjs</div>
      </footer>
    </div>
  )
}

export default Home
